// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Indentifier type for cache_locks */
export type Key = number;

/** Represents the table public.cache_locks */
export default interface CacheLocks {
    key: Key;

    owner: string;

    expiration: number;
}

/** Represents the initializer for the table public.cache_locks */
export interface CacheLocksInitializer {
    key: Key;

    owner: string;

    expiration: number;
}

/** Represents the mutator for the table public.cache_locks */
export interface CacheLocksMutator {
    key?: Key;

    owner?: string;

    expiration?: number;
}
