// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Indentifier type for cache */
export type Key = number;

/** Represents the table public.cache */
export default interface Cache {
    key: Key;

    value: string;

    expiration: number;
}

/** Represents the initializer for the table public.cache */
export interface CacheInitializer {
    key: Key;

    value: string;

    expiration: number;
}

/** Represents the mutator for the table public.cache */
export interface CacheMutator {
    key?: Key;

    value?: string;

    expiration?: number;
}
