// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Indentifier type for job_batches */
export type Id = number;

/** Represents the table public.job_batches */
export default interface JobBatches {
    id: Id;

    name: string;

    total_jobs: number;

    pending_jobs: number;

    failed_jobs: number;

    failed_job_ids: string;

    options: string | null;

    cancelled_at: number | null;

    created_at: number;

    finished_at: number | null;
}

/** Represents the initializer for the table public.job_batches */
export interface JobBatchesInitializer {
    id: Id;

    name: string;

    total_jobs: number;

    pending_jobs: number;

    failed_jobs: number;

    failed_job_ids: string;

    options?: string | null;

    cancelled_at?: number | null;

    created_at: number;

    finished_at?: number | null;
}

/** Represents the mutator for the table public.job_batches */
export interface JobBatchesMutator {
    id?: Id;

    name?: string;

    total_jobs?: number;

    pending_jobs?: number;

    failed_jobs?: number;

    failed_job_ids?: string;

    options?: string | null;

    cancelled_at?: number | null;

    created_at?: number;

    finished_at?: number | null;
}
