// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Indentifier type for migrations */
export type Id = number;

/** Represents the table public.migrations */
export default interface Migrations {
    id: Id;

    migration: string;

    batch: number;
}

/** Represents the initializer for the table public.migrations */
export interface MigrationsInitializer {
    /** Default value: nextval('migrations_id_seq'::regclass) */
    id?: Id;

    migration: string;

    batch: number;
}

/** Represents the mutator for the table public.migrations */
export interface MigrationsMutator {
    id?: Id;

    migration?: string;

    batch?: number;
}
