// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Indentifier type for personal_access_tokens */
export type Id = number;

/** Represents the table public.personal_access_tokens */
export default interface PersonalAccessTokens {
    id: Id;

    tokenable_type: string;

    tokenable_id: string;

    name: string;

    token: string;

    abilities: string | null;

    last_used_at: Date | null;

    expires_at: Date | null;

    created_at: Date | null;

    updated_at: Date | null;
}

/** Represents the initializer for the table public.personal_access_tokens */
export interface PersonalAccessTokensInitializer {
    /** Default value: nextval('personal_access_tokens_id_seq'::regclass) */
    id?: Id;

    tokenable_type: string;

    tokenable_id: string;

    name: string;

    token: string;

    abilities?: string | null;

    last_used_at?: Date | null;

    expires_at?: Date | null;

    created_at?: Date | null;

    updated_at?: Date | null;
}

/** Represents the mutator for the table public.personal_access_tokens */
export interface PersonalAccessTokensMutator {
    id?: Id;

    tokenable_type?: string;

    tokenable_id?: string;

    name?: string;

    token?: string;

    abilities?: string | null;

    last_used_at?: Date | null;

    expires_at?: Date | null;

    created_at?: Date | null;

    updated_at?: Date | null;
}
