// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Indentifier type for sessions */
export type Id = number;

/** Represents the table public.sessions */
export default interface Sessions {
    id: Id;

    user_id: string | null;

    ip_address: string | null;

    user_agent: string | null;

    payload: string;

    last_activity: number;
}

/** Represents the initializer for the table public.sessions */
export interface SessionsInitializer {
    id: Id;

    user_id?: string | null;

    ip_address?: string | null;

    user_agent?: string | null;

    payload: string;

    last_activity: number;
}

/** Represents the mutator for the table public.sessions */
export interface SessionsMutator {
    id?: Id;

    user_id?: string | null;

    ip_address?: string | null;

    user_agent?: string | null;

    payload?: string;

    last_activity?: number;
}
